version: '2.1'

services:
  mongodb:
    image: mongo:6.0.3
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod

  tasks-service:
    build: microservices/tasks-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
      - eureka

  eureka:
    build: spring-cloud/eureka-server
    mem_limit: 512m
    ports:
      - "8761:8761"