server.error.include-message: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  level:
    root: INFO
    org.springframework: DEBUG

management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

server.port: 8080
app.eureka-server: eureka
spring:
  main:
    allow-circular-references: true
  cloud:
    gateway:
      routes:
        - id: default_path_to_data_logic
          uri: lb://data-logic
          predicates:
            - Path=/crm/**

