spring:
  application.name: tasks-service
  datasource:
    url: jdbc:postgresql://postgres:5432/otus
    username: otus
    password: otus123

  liquibase:
    enabled: true
    change-log: liquibase/all_migrations.groovy

server.port: 7002
server.error.include-message: always

app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  level:
    root: INFO

management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

---
spring.config.activate.on-profile: docker

server.port: 8080

app.eureka-server: eureka