spring:

  config.import: "configserver:"
  application.name: data-logic-service
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: ${CONFIG_SERVER_URL}
    username: ${CONFIG_SERVER_USERNAME}
    password: ${CONFIG_SERVER_PASSWORD}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

logging:
  level:
    root: DEBUG
